### PR TITLE
Add support for eslint-plugin-netguru-ember

### PR DESCRIPTION
**Pull request by caseywatts**

### CODE REVIEW

**Comment by Arcanemagus** [comment]
The section headers from https://github.com/netguru/ember-styleguide don't seem to match the rule names from [`eslint-plugin-netguru-ember`](https://github.com/netguru/eslint-plugin-netguru-ember/tree/master/rules), are you sure this works? 😕

**Comment by Arcanemagus** [comment]
It looks like the following rules would work, the other **17** wouldn't:
* `closure-actions`
* `use-brace-expansion`

**Comment by Arcanemagus** [comment]
Well, if I'd bothered to read the issue you linked above, it seems you are already aware of these issues so just comment back here when this is ready 😉.

**Comment by caseywatts** [comment]
Thanks for being on top of this @Arcanemagus :)
We'll open a different PR for this~

**Pull request closed without merging**
