### PR TITLE
Add support for eslint-plugin-prettier

### PR DESCRIPTION
**Pull request by SimenB**

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Does this actually make sense? The link has no dynamic capabilities, and where it is linking to only tells the user how to configure the plugin. Does this plugin even report messages?

**Comment by Arcanemagus** [comment]
Ping @SimenB.

**Comment by SimenB** [comment]
>Does this actually make sense?

I'd like to think so 🙂 

>The link has no dynamic capabilities, and where it is linking to only tells the user how to configure the plugin.

Isn't that that point? At least the second part. There is only a single rule in the plugin, so having it be "dynamic" (if I understand the usage correctly) isn't needed.

>Does this plugin even report messages?

It does report messages (see e.g. https://github.com/zertosh/eslint-plugin-prettify/blob/2fb5dfbb52a2577180bf8fcccb83b3fa7aa4d69c/README.md#sample which was ported in https://github.com/prettier/eslint-plugin-prettier/pull/21)

**Comment by Arcanemagus** [comment]
Sorry, I think when originally looking at this I glossed over the Sample section thinking it was a sample configuration or something? In either case since this only has the one rule this should work, thanks!

Also note that ESLint officially supports a `rule.meta.docs.url` property as of v4.15.0 allowing rules to specify where their documentation exists for anything consuming the rule. I'll be updating the `contributing.md` file shortly here to reflect that 😉.

**Review by Arcanemagus — APPROVED** [review]

**Pull request merged**
