### PR TITLE
Added support for eslint-plugin-standard

### PR DESCRIPTION
**Pull request by apexskier**
Also sorted rules list in `plugins.json` with `:sort` (let me know if you don't want this)

Requested in https://github.com/AtomLinter/linter-eslint/pull/653

### CODE REVIEW

**Comment by Arcanemagus** [comment]
I don't see any reason why the list shouldn't be sorted, but as I don't know why it wasn't in the first place I'll leave it to @jfmengels to merge 😉.

**Comment by jfmengels** [comment]
Thanks @apexskier!

It was my purpose to sort it, but my Atom sorting plugin doesn't sort in the same order as your vim tool I think (but this is fine).

When I created this plugin, I added a bunch of plugins I found in awesome-eslint, but I skipped over those that didn't have any dedicated link per rule. Like in this case, eslint-plugin-standard does not really have a dedicated page.

Do you think it's fine like this (I agree that having this is better than nothing), or should we take the opportunity to file an issue in that plugin's repo to request having dedicated rule documentation pages?

**Comment by apexskier** [comment]
Whatever on the sorting, I'd be okay if it changed, since it's totally opaque to users. 

I'm totally fine not linking directly to each rule, especially since there are only 3 in this case. I'd open an issue with the plugin's repo letting them know they have suboptimal integration, but I wouldn't push too hard for them to change if the maintainer doesn't want to.

**Comment by jfmengels** [comment]
> I wouldn't push too hard for them to change if the maintainer doesn't want to.

Same here. I'd really appreciate it if you opened an issue :)

I'm fine with this as it is then. Let's merge and update it should the author update it docs :)

**Pull request merged**
